// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/AgreementService.proto

package com.protobuf.demo;

public final class AgreementService {
  private AgreementService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 agr_no = 1;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    boolean hasAgrNo();
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    int getAgrNo();

    // required int32 page = 2;
    /**
     * <code>required int32 page = 2;</code>
     */
    boolean hasPage();
    /**
     * <code>required int32 page = 2;</code>
     */
    int getPage();

    // required int32 page_number = 3;
    /**
     * <code>required int32 page_number = 3;</code>
     */
    boolean hasPageNumber();
    /**
     * <code>required int32 page_number = 3;</code>
     */
    int getPageNumber();
  }
  /**
   * Protobuf type {@code com.protobuf.demo.Request}
   */
  public static final class Request extends
      com.google.protobuf.GeneratedMessage
      implements RequestOrBuilder {
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Request(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Request defaultInstance;
    public static Request getDefaultInstance() {
      return defaultInstance;
    }

    public Request getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              agrNo_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              page_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Request_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.demo.AgreementService.Request.class, com.protobuf.demo.AgreementService.Request.Builder.class);
    }

    public static com.google.protobuf.Parser<Request> PARSER =
        new com.google.protobuf.AbstractParser<Request>() {
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 agr_no = 1;
    public static final int AGR_NO_FIELD_NUMBER = 1;
    private int agrNo_;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public boolean hasAgrNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public int getAgrNo() {
      return agrNo_;
    }

    // required int32 page = 2;
    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>required int32 page = 2;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    // required int32 page_number = 3;
    public static final int PAGE_NUMBER_FIELD_NUMBER = 3;
    private int pageNumber_;
    /**
     * <code>required int32 page_number = 3;</code>
     */
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 page_number = 3;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    private void initFields() {
      agrNo_ = 0;
      page_ = 0;
      pageNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAgrNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pageNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.demo.AgreementService.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.demo.AgreementService.Request prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.demo.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protobuf.demo.AgreementService.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Request_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.demo.AgreementService.Request.class, com.protobuf.demo.AgreementService.Request.Builder.class);
      }

      // Construct using com.protobuf.demo.AgreementService.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        agrNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Request_descriptor;
      }

      public com.protobuf.demo.AgreementService.Request getDefaultInstanceForType() {
        return com.protobuf.demo.AgreementService.Request.getDefaultInstance();
      }

      public com.protobuf.demo.AgreementService.Request build() {
        com.protobuf.demo.AgreementService.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.demo.AgreementService.Request buildPartial() {
        com.protobuf.demo.AgreementService.Request result = new com.protobuf.demo.AgreementService.Request(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.agrNo_ = agrNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageNumber_ = pageNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.demo.AgreementService.Request) {
          return mergeFrom((com.protobuf.demo.AgreementService.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.demo.AgreementService.Request other) {
        if (other == com.protobuf.demo.AgreementService.Request.getDefaultInstance()) return this;
        if (other.hasAgrNo()) {
          setAgrNo(other.getAgrNo());
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAgrNo()) {
          
          return false;
        }
        if (!hasPage()) {
          
          return false;
        }
        if (!hasPageNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.demo.AgreementService.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.demo.AgreementService.Request) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 agr_no = 1;
      private int agrNo_ ;
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public boolean hasAgrNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public int getAgrNo() {
        return agrNo_;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder setAgrNo(int value) {
        bitField0_ |= 0x00000001;
        agrNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder clearAgrNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        agrNo_ = 0;
        onChanged();
        return this;
      }

      // required int32 page = 2;
      private int page_ ;
      /**
       * <code>required int32 page = 2;</code>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000002;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        page_ = 0;
        onChanged();
        return this;
      }

      // required int32 page_number = 3;
      private int pageNumber_ ;
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000004;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.protobuf.demo.Request)
    }

    static {
      defaultInstance = new Request(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.demo.Request)
  }

  public interface AgreementOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 agr_no = 1;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    boolean hasAgrNo();
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    int getAgrNo();

    // required int32 rebate_cate = 2;
    /**
     * <code>required int32 rebate_cate = 2;</code>
     */
    boolean hasRebateCate();
    /**
     * <code>required int32 rebate_cate = 2;</code>
     */
    int getRebateCate();
  }
  /**
   * Protobuf type {@code com.protobuf.demo.Agreement}
   */
  public static final class Agreement extends
      com.google.protobuf.GeneratedMessage
      implements AgreementOrBuilder {
    // Use Agreement.newBuilder() to construct.
    private Agreement(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Agreement(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Agreement defaultInstance;
    public static Agreement getDefaultInstance() {
      return defaultInstance;
    }

    public Agreement getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Agreement(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              agrNo_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              rebateCate_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Agreement_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Agreement_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.demo.AgreementService.Agreement.class, com.protobuf.demo.AgreementService.Agreement.Builder.class);
    }

    public static com.google.protobuf.Parser<Agreement> PARSER =
        new com.google.protobuf.AbstractParser<Agreement>() {
      public Agreement parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Agreement(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Agreement> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 agr_no = 1;
    public static final int AGR_NO_FIELD_NUMBER = 1;
    private int agrNo_;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public boolean hasAgrNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public int getAgrNo() {
      return agrNo_;
    }

    // required int32 rebate_cate = 2;
    public static final int REBATE_CATE_FIELD_NUMBER = 2;
    private int rebateCate_;
    /**
     * <code>required int32 rebate_cate = 2;</code>
     */
    public boolean hasRebateCate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 rebate_cate = 2;</code>
     */
    public int getRebateCate() {
      return rebateCate_;
    }

    private void initFields() {
      agrNo_ = 0;
      rebateCate_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAgrNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRebateCate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, rebateCate_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, rebateCate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Agreement parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.demo.AgreementService.Agreement prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.demo.Agreement}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protobuf.demo.AgreementService.AgreementOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Agreement_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Agreement_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.demo.AgreementService.Agreement.class, com.protobuf.demo.AgreementService.Agreement.Builder.class);
      }

      // Construct using com.protobuf.demo.AgreementService.Agreement.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        agrNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        rebateCate_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Agreement_descriptor;
      }

      public com.protobuf.demo.AgreementService.Agreement getDefaultInstanceForType() {
        return com.protobuf.demo.AgreementService.Agreement.getDefaultInstance();
      }

      public com.protobuf.demo.AgreementService.Agreement build() {
        com.protobuf.demo.AgreementService.Agreement result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.demo.AgreementService.Agreement buildPartial() {
        com.protobuf.demo.AgreementService.Agreement result = new com.protobuf.demo.AgreementService.Agreement(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.agrNo_ = agrNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.rebateCate_ = rebateCate_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.demo.AgreementService.Agreement) {
          return mergeFrom((com.protobuf.demo.AgreementService.Agreement)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.demo.AgreementService.Agreement other) {
        if (other == com.protobuf.demo.AgreementService.Agreement.getDefaultInstance()) return this;
        if (other.hasAgrNo()) {
          setAgrNo(other.getAgrNo());
        }
        if (other.hasRebateCate()) {
          setRebateCate(other.getRebateCate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAgrNo()) {
          
          return false;
        }
        if (!hasRebateCate()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.demo.AgreementService.Agreement parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.demo.AgreementService.Agreement) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 agr_no = 1;
      private int agrNo_ ;
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public boolean hasAgrNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public int getAgrNo() {
        return agrNo_;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder setAgrNo(int value) {
        bitField0_ |= 0x00000001;
        agrNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder clearAgrNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        agrNo_ = 0;
        onChanged();
        return this;
      }

      // required int32 rebate_cate = 2;
      private int rebateCate_ ;
      /**
       * <code>required int32 rebate_cate = 2;</code>
       */
      public boolean hasRebateCate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 rebate_cate = 2;</code>
       */
      public int getRebateCate() {
        return rebateCate_;
      }
      /**
       * <code>required int32 rebate_cate = 2;</code>
       */
      public Builder setRebateCate(int value) {
        bitField0_ |= 0x00000002;
        rebateCate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 rebate_cate = 2;</code>
       */
      public Builder clearRebateCate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        rebateCate_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.protobuf.demo.Agreement)
    }

    static {
      defaultInstance = new Agreement(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.demo.Agreement)
  }

  public interface ResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.protobuf.demo.Agreement agreements = 1;
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    java.util.List<com.protobuf.demo.AgreementService.Agreement> 
        getAgreementsList();
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    com.protobuf.demo.AgreementService.Agreement getAgreements(int index);
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    int getAgreementsCount();
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    java.util.List<? extends com.protobuf.demo.AgreementService.AgreementOrBuilder> 
        getAgreementsOrBuilderList();
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    com.protobuf.demo.AgreementService.AgreementOrBuilder getAgreementsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.protobuf.demo.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessage
      implements ResponseOrBuilder {
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Response(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Response defaultInstance;
    public static Response getDefaultInstance() {
      return defaultInstance;
    }

    public Response getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                agreements_ = new java.util.ArrayList<com.protobuf.demo.AgreementService.Agreement>();
                mutable_bitField0_ |= 0x00000001;
              }
              agreements_.add(input.readMessage(com.protobuf.demo.AgreementService.Agreement.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          agreements_ = java.util.Collections.unmodifiableList(agreements_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Response_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.demo.AgreementService.Response.class, com.protobuf.demo.AgreementService.Response.Builder.class);
    }

    public static com.google.protobuf.Parser<Response> PARSER =
        new com.google.protobuf.AbstractParser<Response>() {
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    // repeated .com.protobuf.demo.Agreement agreements = 1;
    public static final int AGREEMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.protobuf.demo.AgreementService.Agreement> agreements_;
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    public java.util.List<com.protobuf.demo.AgreementService.Agreement> getAgreementsList() {
      return agreements_;
    }
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    public java.util.List<? extends com.protobuf.demo.AgreementService.AgreementOrBuilder> 
        getAgreementsOrBuilderList() {
      return agreements_;
    }
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    public int getAgreementsCount() {
      return agreements_.size();
    }
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    public com.protobuf.demo.AgreementService.Agreement getAgreements(int index) {
      return agreements_.get(index);
    }
    /**
     * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
     */
    public com.protobuf.demo.AgreementService.AgreementOrBuilder getAgreementsOrBuilder(
        int index) {
      return agreements_.get(index);
    }

    private void initFields() {
      agreements_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      for (int i = 0; i < getAgreementsCount(); i++) {
        if (!getAgreements(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < agreements_.size(); i++) {
        output.writeMessage(1, agreements_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < agreements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, agreements_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.demo.AgreementService.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.demo.AgreementService.Response prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.demo.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protobuf.demo.AgreementService.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Response_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.demo.AgreementService.Response.class, com.protobuf.demo.AgreementService.Response.Builder.class);
      }

      // Construct using com.protobuf.demo.AgreementService.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAgreementsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (agreementsBuilder_ == null) {
          agreements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          agreementsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_Response_descriptor;
      }

      public com.protobuf.demo.AgreementService.Response getDefaultInstanceForType() {
        return com.protobuf.demo.AgreementService.Response.getDefaultInstance();
      }

      public com.protobuf.demo.AgreementService.Response build() {
        com.protobuf.demo.AgreementService.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.demo.AgreementService.Response buildPartial() {
        com.protobuf.demo.AgreementService.Response result = new com.protobuf.demo.AgreementService.Response(this);
        int from_bitField0_ = bitField0_;
        if (agreementsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            agreements_ = java.util.Collections.unmodifiableList(agreements_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.agreements_ = agreements_;
        } else {
          result.agreements_ = agreementsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.demo.AgreementService.Response) {
          return mergeFrom((com.protobuf.demo.AgreementService.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.demo.AgreementService.Response other) {
        if (other == com.protobuf.demo.AgreementService.Response.getDefaultInstance()) return this;
        if (agreementsBuilder_ == null) {
          if (!other.agreements_.isEmpty()) {
            if (agreements_.isEmpty()) {
              agreements_ = other.agreements_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAgreementsIsMutable();
              agreements_.addAll(other.agreements_);
            }
            onChanged();
          }
        } else {
          if (!other.agreements_.isEmpty()) {
            if (agreementsBuilder_.isEmpty()) {
              agreementsBuilder_.dispose();
              agreementsBuilder_ = null;
              agreements_ = other.agreements_;
              bitField0_ = (bitField0_ & ~0x00000001);
              agreementsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAgreementsFieldBuilder() : null;
            } else {
              agreementsBuilder_.addAllMessages(other.agreements_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getAgreementsCount(); i++) {
          if (!getAgreements(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.demo.AgreementService.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.demo.AgreementService.Response) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.protobuf.demo.Agreement agreements = 1;
      private java.util.List<com.protobuf.demo.AgreementService.Agreement> agreements_ =
        java.util.Collections.emptyList();
      private void ensureAgreementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          agreements_ = new java.util.ArrayList<com.protobuf.demo.AgreementService.Agreement>(agreements_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.demo.AgreementService.Agreement, com.protobuf.demo.AgreementService.Agreement.Builder, com.protobuf.demo.AgreementService.AgreementOrBuilder> agreementsBuilder_;

      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public java.util.List<com.protobuf.demo.AgreementService.Agreement> getAgreementsList() {
        if (agreementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(agreements_);
        } else {
          return agreementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public int getAgreementsCount() {
        if (agreementsBuilder_ == null) {
          return agreements_.size();
        } else {
          return agreementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public com.protobuf.demo.AgreementService.Agreement getAgreements(int index) {
        if (agreementsBuilder_ == null) {
          return agreements_.get(index);
        } else {
          return agreementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder setAgreements(
          int index, com.protobuf.demo.AgreementService.Agreement value) {
        if (agreementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgreementsIsMutable();
          agreements_.set(index, value);
          onChanged();
        } else {
          agreementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder setAgreements(
          int index, com.protobuf.demo.AgreementService.Agreement.Builder builderForValue) {
        if (agreementsBuilder_ == null) {
          ensureAgreementsIsMutable();
          agreements_.set(index, builderForValue.build());
          onChanged();
        } else {
          agreementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder addAgreements(com.protobuf.demo.AgreementService.Agreement value) {
        if (agreementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgreementsIsMutable();
          agreements_.add(value);
          onChanged();
        } else {
          agreementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder addAgreements(
          int index, com.protobuf.demo.AgreementService.Agreement value) {
        if (agreementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAgreementsIsMutable();
          agreements_.add(index, value);
          onChanged();
        } else {
          agreementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder addAgreements(
          com.protobuf.demo.AgreementService.Agreement.Builder builderForValue) {
        if (agreementsBuilder_ == null) {
          ensureAgreementsIsMutable();
          agreements_.add(builderForValue.build());
          onChanged();
        } else {
          agreementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder addAgreements(
          int index, com.protobuf.demo.AgreementService.Agreement.Builder builderForValue) {
        if (agreementsBuilder_ == null) {
          ensureAgreementsIsMutable();
          agreements_.add(index, builderForValue.build());
          onChanged();
        } else {
          agreementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder addAllAgreements(
          java.lang.Iterable<? extends com.protobuf.demo.AgreementService.Agreement> values) {
        if (agreementsBuilder_ == null) {
          ensureAgreementsIsMutable();
          super.addAll(values, agreements_);
          onChanged();
        } else {
          agreementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder clearAgreements() {
        if (agreementsBuilder_ == null) {
          agreements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          agreementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public Builder removeAgreements(int index) {
        if (agreementsBuilder_ == null) {
          ensureAgreementsIsMutable();
          agreements_.remove(index);
          onChanged();
        } else {
          agreementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public com.protobuf.demo.AgreementService.Agreement.Builder getAgreementsBuilder(
          int index) {
        return getAgreementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public com.protobuf.demo.AgreementService.AgreementOrBuilder getAgreementsOrBuilder(
          int index) {
        if (agreementsBuilder_ == null) {
          return agreements_.get(index);  } else {
          return agreementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public java.util.List<? extends com.protobuf.demo.AgreementService.AgreementOrBuilder> 
           getAgreementsOrBuilderList() {
        if (agreementsBuilder_ != null) {
          return agreementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(agreements_);
        }
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public com.protobuf.demo.AgreementService.Agreement.Builder addAgreementsBuilder() {
        return getAgreementsFieldBuilder().addBuilder(
            com.protobuf.demo.AgreementService.Agreement.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public com.protobuf.demo.AgreementService.Agreement.Builder addAgreementsBuilder(
          int index) {
        return getAgreementsFieldBuilder().addBuilder(
            index, com.protobuf.demo.AgreementService.Agreement.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protobuf.demo.Agreement agreements = 1;</code>
       */
      public java.util.List<com.protobuf.demo.AgreementService.Agreement.Builder> 
           getAgreementsBuilderList() {
        return getAgreementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.protobuf.demo.AgreementService.Agreement, com.protobuf.demo.AgreementService.Agreement.Builder, com.protobuf.demo.AgreementService.AgreementOrBuilder> 
          getAgreementsFieldBuilder() {
        if (agreementsBuilder_ == null) {
          agreementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.protobuf.demo.AgreementService.Agreement, com.protobuf.demo.AgreementService.Agreement.Builder, com.protobuf.demo.AgreementService.AgreementOrBuilder>(
                  agreements_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          agreements_ = null;
        }
        return agreementsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.protobuf.demo.Response)
    }

    static {
      defaultInstance = new Response(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.demo.Response)
  }

  public interface JavaBeanOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 agr_no = 1;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    boolean hasAgrNo();
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    int getAgrNo();

    // required int32 page = 2;
    /**
     * <code>required int32 page = 2;</code>
     */
    boolean hasPage();
    /**
     * <code>required int32 page = 2;</code>
     */
    int getPage();

    // required int32 page_number = 3;
    /**
     * <code>required int32 page_number = 3;</code>
     */
    boolean hasPageNumber();
    /**
     * <code>required int32 page_number = 3;</code>
     */
    int getPageNumber();
  }
  /**
   * Protobuf type {@code com.protobuf.demo.JavaBean}
   */
  public static final class JavaBean extends
      com.google.protobuf.GeneratedMessage
      implements JavaBeanOrBuilder {
    // Use JavaBean.newBuilder() to construct.
    private JavaBean(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JavaBean(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JavaBean defaultInstance;
    public static JavaBean getDefaultInstance() {
      return defaultInstance;
    }

    public JavaBean getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JavaBean(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              agrNo_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              page_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              pageNumber_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_JavaBean_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_JavaBean_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protobuf.demo.AgreementService.JavaBean.class, com.protobuf.demo.AgreementService.JavaBean.Builder.class);
    }

    public static com.google.protobuf.Parser<JavaBean> PARSER =
        new com.google.protobuf.AbstractParser<JavaBean>() {
      public JavaBean parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JavaBean(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JavaBean> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 agr_no = 1;
    public static final int AGR_NO_FIELD_NUMBER = 1;
    private int agrNo_;
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public boolean hasAgrNo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 agr_no = 1;</code>
     */
    public int getAgrNo() {
      return agrNo_;
    }

    // required int32 page = 2;
    public static final int PAGE_FIELD_NUMBER = 2;
    private int page_;
    /**
     * <code>required int32 page = 2;</code>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 page = 2;</code>
     */
    public int getPage() {
      return page_;
    }

    // required int32 page_number = 3;
    public static final int PAGE_NUMBER_FIELD_NUMBER = 3;
    private int pageNumber_;
    /**
     * <code>required int32 page_number = 3;</code>
     */
    public boolean hasPageNumber() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 page_number = 3;</code>
     */
    public int getPageNumber() {
      return pageNumber_;
    }

    private void initFields() {
      agrNo_ = 0;
      page_ = 0;
      pageNumber_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasAgrNo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPageNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, pageNumber_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, agrNo_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, page_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, pageNumber_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.protobuf.demo.AgreementService.JavaBean parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.protobuf.demo.AgreementService.JavaBean prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protobuf.demo.JavaBean}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.protobuf.demo.AgreementService.JavaBeanOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_JavaBean_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_JavaBean_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protobuf.demo.AgreementService.JavaBean.class, com.protobuf.demo.AgreementService.JavaBean.Builder.class);
      }

      // Construct using com.protobuf.demo.AgreementService.JavaBean.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        agrNo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        pageNumber_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protobuf.demo.AgreementService.internal_static_com_protobuf_demo_JavaBean_descriptor;
      }

      public com.protobuf.demo.AgreementService.JavaBean getDefaultInstanceForType() {
        return com.protobuf.demo.AgreementService.JavaBean.getDefaultInstance();
      }

      public com.protobuf.demo.AgreementService.JavaBean build() {
        com.protobuf.demo.AgreementService.JavaBean result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.protobuf.demo.AgreementService.JavaBean buildPartial() {
        com.protobuf.demo.AgreementService.JavaBean result = new com.protobuf.demo.AgreementService.JavaBean(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.agrNo_ = agrNo_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.pageNumber_ = pageNumber_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protobuf.demo.AgreementService.JavaBean) {
          return mergeFrom((com.protobuf.demo.AgreementService.JavaBean)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protobuf.demo.AgreementService.JavaBean other) {
        if (other == com.protobuf.demo.AgreementService.JavaBean.getDefaultInstance()) return this;
        if (other.hasAgrNo()) {
          setAgrNo(other.getAgrNo());
        }
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasPageNumber()) {
          setPageNumber(other.getPageNumber());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasAgrNo()) {
          
          return false;
        }
        if (!hasPage()) {
          
          return false;
        }
        if (!hasPageNumber()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protobuf.demo.AgreementService.JavaBean parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protobuf.demo.AgreementService.JavaBean) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 agr_no = 1;
      private int agrNo_ ;
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public boolean hasAgrNo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public int getAgrNo() {
        return agrNo_;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder setAgrNo(int value) {
        bitField0_ |= 0x00000001;
        agrNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 agr_no = 1;</code>
       */
      public Builder clearAgrNo() {
        bitField0_ = (bitField0_ & ~0x00000001);
        agrNo_ = 0;
        onChanged();
        return this;
      }

      // required int32 page = 2;
      private int page_ ;
      /**
       * <code>required int32 page = 2;</code>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000002;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page = 2;</code>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        page_ = 0;
        onChanged();
        return this;
      }

      // required int32 page_number = 3;
      private int pageNumber_ ;
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public boolean hasPageNumber() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public int getPageNumber() {
        return pageNumber_;
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public Builder setPageNumber(int value) {
        bitField0_ |= 0x00000004;
        pageNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 page_number = 3;</code>
       */
      public Builder clearPageNumber() {
        bitField0_ = (bitField0_ & ~0x00000004);
        pageNumber_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.protobuf.demo.JavaBean)
    }

    static {
      defaultInstance = new JavaBean(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.protobuf.demo.JavaBean)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_demo_Request_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobuf_demo_Request_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_demo_Agreement_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobuf_demo_Agreement_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_demo_Response_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobuf_demo_Response_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protobuf_demo_JavaBean_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_protobuf_demo_JavaBean_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/protobuf/AgreementService.pro" +
      "to\022\021com.protobuf.demo\"<\n\007Request\022\016\n\006agr_" +
      "no\030\001 \002(\005\022\014\n\004page\030\002 \002(\005\022\023\n\013page_number\030\003 " +
      "\002(\005\"0\n\tAgreement\022\016\n\006agr_no\030\001 \002(\005\022\023\n\013reba" +
      "te_cate\030\002 \002(\005\"<\n\010Response\0220\n\nagreements\030" +
      "\001 \003(\0132\034.com.protobuf.demo.Agreement\"=\n\010J" +
      "avaBean\022\016\n\006agr_no\030\001 \002(\005\022\014\n\004page\030\002 \002(\005\022\023\n" +
      "\013page_number\030\003 \002(\005"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_protobuf_demo_Request_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_protobuf_demo_Request_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobuf_demo_Request_descriptor,
              new java.lang.String[] { "AgrNo", "Page", "PageNumber", });
          internal_static_com_protobuf_demo_Agreement_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_protobuf_demo_Agreement_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobuf_demo_Agreement_descriptor,
              new java.lang.String[] { "AgrNo", "RebateCate", });
          internal_static_com_protobuf_demo_Response_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_protobuf_demo_Response_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobuf_demo_Response_descriptor,
              new java.lang.String[] { "Agreements", });
          internal_static_com_protobuf_demo_JavaBean_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_protobuf_demo_JavaBean_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_protobuf_demo_JavaBean_descriptor,
              new java.lang.String[] { "AgrNo", "Page", "PageNumber", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
